import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import Header from './components/Header/Header';

const nanumSquareBold = localFont({
  src: '../public/fonts/NanumSquare-Bold.ttf',
  variable: '--font-nanumSquareBold',
});

const nanumSquareRegular = localFont({
  src: '../public/fonts/NanumSquare-Regular.ttf',
  variable: '--font-nanumSquareRegular',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${nanumSquareBold.variable} ${nanumSquareRegular.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
